
spring:
  application.name: "playsite-manager"
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximumPoolSize: 8
  liquibase:
    change-log: classpath:liquibase/master-changelog.xml
    enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.jdbc.time_zone: UTC
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true

server:
  port: 8090

#Logging
logging.level.root: INFO
logging.level.com.app.ref: DEBUG
